---
title: "R Notebook"
output: html_notebook
---

Functions
```{r}
pow_two <- function(x, print_info = TRUE){
  y <- x^2
  if(print_info){
    print(paste(x, "to the power two equals ", y))
  }
  return (y)
}

result <- pow_two(3)
result <- pow_two(4, FALSE)
result
```
function scoping
```{r}
pow_two <- fucntion(x){
  y=x^2
  return (y)
}

pow_two(4)
y
x

```
r passes arguments by value
```{r}

triple <- function(x){
  x <- 3*x
  x
}

a<-5
triple(a)
a

```
other type of parameters
```{r}
linkedin <- c(16,9,13,5,2,17,14)

interpret <- function(num_views){
  if(num_views>15){
    print("you´re popular")
    return(num_views)
  }
  else{
    print("Try to be more visible!")
    return(0)
  }
}

interpret(linkedin[1])

interpret_all <- function(views, return_sum=TRUE){
  count <- 0
  for (v in views){
    count<- count + interpret(v)
  }
  if(return_sum){
    return(count)
  }else{
    return(NULL)
  }
    
}
interpret_all(linkedin)
```
Load an R package
```{r}

library(ggplot2)
qplot(mtcars$wt, mtcars$hp)
```
apply with R

```{r}

temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

lapply(temp, min)

for(t in temp){
  print(min(t))
}

select <- function(x){
  print(paste("this collection contains total = ", sum(x)))
}

list<- lapply(temp, select)
list
```
lapply and anonymous functions
```{r}

(function(x){3*x})(9)

pioneers <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623", "PEARSON:1857")
split <- strsplit(pioneers,split = ":")

split

split_low <- lapply(split,tolower)

names <- lapply(split_low,function(x){x[1]})
names

years <- lapply(split_low,function(x){x[2]})
years
```
use lapply with additional arguments

```{r}

select_el <- function(x, index){
  x[index]
}

names <- lapply(split_low, select_el,1)  
names

years <- lapply(split_low, select_el,2)
years
```

utilities

```{r}

errors<- c(1.9, -2.6, 4.0, -9.5, -3.4, 7.3)
print (sum(abs(round(errors))))

?round


```

grep & grepl

```{r}

emails <- c("john.doe@ivyleague.edu", "education@world.gov", "dalai.lama@peace.org",
            "invalid.edu", "quant@bigdatacollege.edu", "cookie.monster@sesame.tv")

grepl(pattern="edu", x=emails)

grep(pattern="edu", x=emails)


```




