---
title: "R Notebook"
output: html_notebook
---

introduction to the tidyverse

```{r}
library(gapminder)
library(dplyr)

gapminder


```
filtering
```{r}

gapminder %>%
  filter(year==1957)
```
Arrange
```{r}

gapminder %>%
  arrange(lifeExp)

gapminder %>%
  arrange(desc(lifeExp))
```
filtering and arranging
```{r}

gapminder %>%
  filter(year==1957) %>%
  arrange(desc(pop))
```
the verb mutate
```{r}

gapminder %>%
  mutate(lifeExp = 12 * lifeExp)

gapminder %>%
  mutate(lifeExpMonths = 12 * lifeExp)

```
combining filter, mutate and arrange
```{r}

gapminder %>%
  filter(year==2007) %>%
  mutate(lifeExpMonths = 12 * lifeExp) %>%
  arrange(desc(lifeExpMonths))
```
```{r}

library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year==1952)

gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) +
  geom_point()
```
log scaling

```{r}
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

```
```{r}

ggplot(gapminder_1952, aes(x=pop, y=lifeExp,color=continent)) +
  geom_point() +
  scale_x_log10() 

```

```{r}
ggplot(gapminder_1952, aes(x=pop, y=lifeExp,color=continent, size = gdpPercap)) +
  geom_point() +
  scale_x_log10() 
```
```{r}
gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y = lifeExp)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~ continent)
```

```{r}
ggplot(gapminder, aes(x=gdpPercap, y = lifeExp)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~ year)
```

